/*
 * This file is used by Code Analysis to maintain SuppressMessage
 * attributes that are applied to this project.
 * Project-level suppressions either have no target or are given
 * a specific target and scoped to a namespace, type, member, etc.
 */

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Naming",
    "AV1755:Name of async method should end with Async or TaskAsync",
    Justification = "Using Async as a suffix on test methods would be distracting.")]

[assembly: SuppressMessage(
    "Design",
    "CA1034:Nested types should not be visible",
    Justification = "This project uses nested types to group tests.")]

[assembly: SuppressMessage(
    "Naming",
    "CA1707:Identifiers should not contain underscores",
    Justification = "This project uses underscores in test names.")]

[assembly: SuppressMessage(
    "Redundancy",
    "RCS1163:Unused parameter.",
    Justification = "Test delegates have unused parameters.")]

[assembly: SuppressMessage(
    "Redundancies in Symbol Declarations",
    "RECS0154:Parameter is never used",
    Justification = "Generated code is not under our control",
    Scope = "type",
    Target = "~T:AutoGeneratedProgram")]

[assembly: SuppressMessage(
    "StyleCop.CSharp.DocumentationRules",
    "SA0001:Enable XML documentation output",
    Justification = "This project contains unit tests and doesn't need Xml documentation enabled as there is no consumer.")]

[assembly: SuppressMessage(
    "StyleCop.CSharp.ReadabilityRules",
    "SA1101:Prefix local calls with this",
    Justification = "Using 'this' where not required by the language creates clutter and obfuscates code")]

// There's a persistent myth that placing using directives within namespaces improves compiler performance
// This was never true with the original compiler and it's not true with the Roslyn compiler either.
[assembly: SuppressMessage(
    "StyleCop.CSharp.OrderingRules",
    "SA1200:Using directives must be placed correctly",
    Justification = "Using statements belong at the top of the file.")]

[assembly: SuppressMessage(
    "StyleCop.CSharp.NamingRules",
    "SA1309:FieldNamesMustNotBeginWithUnderscore",
    Justification = "This project chooses to use _ to prefix private fields.")]

[assembly: SuppressMessage(
    "StyleCop.CSharp.DocumentationRules",
    "SA1633:File must have header",
    Justification = "Source code files files don't need a file header.")]

[assembly: SuppressMessage(
    "StyleCop.CSharp.DocumentationRules",
    "SA1652:Enable XML documentation output",
    Justification = "This project contains unit tests and doesn't need Xml documentation enabled as there is no consumer.")]
